name: Descargar ICS Teamup

on:
  schedule:
    - cron: '50 8 * * *'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v4

      - name: Descargar ICS
        run: |
          curl -L "https://ics.teamup.com/feed/ksdib8z2y3ig3osyxy/11443673.ics" -o teamup.ics

      - name: Commit y push si cambió
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add teamup.ics
          git diff --cached --quiet || git commit -m "Actualiza ICS"
          git push
